version: '3'

services:
  api-solid-pg:
    image: bitname/postgresql
    ports: 
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid